### ISSUE TITLE
Unable to find image 'ghcr.io/captn3m0/forteller-dl:main' locally

### ISSUE THREAD

**Issue by reezic** [captn3m0/forteller-dl#3]
Running in docker on windows from the root folder of the repository, I get the following error:

```
Unable to find image 'ghcr.io/captn3m0/forteller-dl:main' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/captn3m0/forteller-dl/manifests/main": unauthorized.
```

I run the command as:
docker run -it --init --volume "C:\Users\einar\Downloads\Gloomhaven:\downloads" --env-file .env ghcr.io/captn3m0/forteller-dl:main ceph_gh /downloads

**Comment by captn3m0** [comment]
You will need to authenticate to the GitHub Container Registry first: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry

**Comment by captn3m0** [comment]
Put instructions for this in the README.
