### ISSUE TITLE
Uncaught Exception: 400: {"message":"Unable to find user profile"}

### ISSUE THREAD

**Issue by reezic** [captn3m0/forteller-dl#4]
Running this in PHP, I get the following error after having downloaded a few of the audio files from "ceph_gh":

`Uncaught Exception: 400: {"message":"Unable to find user profile"}`

Could this be related to me having created my account on Forteller very recently? I saw you mention something like that in the other issue.

**Comment by captn3m0** [comment]
It's possible that the token expired, so if you re-run the script again, it should just fetch a new token and download the remaining files. The script will not re-download already downloaded files, as long as they aren't renamed.

Let me know if this doesn't work.

**Comment by reezic** [comment]
Unfortunately that didn't seem to work:

```
Fetching https://us-central1-forteller-platform.cloudfunctions.net/games

Fetching https://us-central1-forteller-platform.cloudfunctions.net/games/3lb9EUUaVA1U97NxcnTE/containers

Fetching https://us-central1-forteller-platform.cloudfunctions.net/games/3lb9EUUaVA1U97NxcnTE/containers/Fr4vHrsGjHj0eWwjkhR2/items

C:\Users\einar\Downloads\Gloomhaven\forteller-dl/Gloomhaven/Prologue - Introduction.mp3

Fetching https://us-central1-forteller-platform.cloudfunctions.net/games/3lb9EUUaVA1U97NxcnTE/containers/vGthNDJVJlFSWlpid5SL/items

C:\Users\einar\Downloads\Gloomhaven\forteller-dl/Gloomhaven/1 The Black Barrow - Introduction.mp3

C:\Users\einar\Downloads\Gloomhaven\forteller-dl/Gloomhaven/1 The Black Barrow - Trigger 1.mp3

C:\Users\einar\Downloads\Gloomhaven\forteller-dl/Gloomhaven/1 The Black Barrow - Conclusion.mp3

Fetching https://us-central1-forteller-platform.cloudfunctions.net/games/3lb9EUUaVA1U97NxcnTE/containers/xrieHh3KLp3xv2hGWndX/items

C:\Users\einar\Downloads\Gloomhaven\forteller-dl/Gloomhaven/2 Barrow Lair - Introduction.mp3

Fetching https://us-central1-forteller-platform.cloudfunctions.net/audio/j9lSZoX5itKJLGSUOFdQ/KxVvlfjcxo8kiypM2FqO/1T6yPf8Q9kxkh02z28Zh

PHP Fatal error:  Uncaught Exception: 400: {"message":"Unable to find user profile"} in C:\Users\einar\Downloads\Gloomhaven\forteller-dl\run.php:31

Stack trace:
#0 C:\Users\einar\Downloads\Gloomhaven\forteller-dl\run.php(89): doCurl()
#1 C:\Users\einar\Downloads\Gloomhaven\forteller-dl\run.php(147): request()
#2 {main}

  thrown in C:\Users\einar\Downloads\Gloomhaven\forteller-dl\run.php on line 31
```

**Comment by Sive0n** [comment]
Having the same issue.
I did some modifications for testing purposes and it seems that fetching item information (in order to get the "streamUri") works just fine, even for SKUs I don't have. Fetching audio via the "streamUri" however fails on all the files besides the first 3 (in my case for the ceph_jaws SKU).

**Comment by captn3m0** [comment]
The first few files are available for demo purposes to all users, so that's expected.

I couldn't replicate the unable to find user profile error, but now that the streams are DRM protected (See https://github.com/captn3m0/forteller-dl/issues/1#issuecomment-1145862893), it won't be helpful much.

**Comment by captn3m0** [comment]
Closing this, the APIs have changed a lot since. Please see https://github.com/captn3m0/forteller-dl/issues/1#issuecomment-1499012610 for a working implementation via `yt-dlp` instead that uses the new APIs.
